## Configuration file for metagene profiling

# Input files
alignmentDirPath: "/home/user/SPP2002/synechocystis_metagene_analysis/run_TTS/bam/"
annotationFilePath: "/home/user/SPP2002/synechocystis_metagene_analysis/annotations/annotation_filtered.gff"
genomeFilePath: "/home/user/SPP2002/synechocystis_metagene_analysis/genome.fa"

# Output folder
outputDirPath: "metagene_TTS"

### Metagene settings
# Window on which the metagene profiling is performed
# Number of nucleotides upstream of each annotated ORF that will be considered
positionsOutsideORF: 200
# Number of nucleotides in each annotated ORF that will be considered
positionsInsideORF: 150

# methods to filter the input annotation before metagene profiling is performed (overlap, length and/or rpkm)
filteringMethods: [overlap, length, rpkm]

# Distance around each annotated genes that will be considered for removing overlapping genes
# neighboringGenesDistance 0 only removes directly overlapping genes.
neighboringGenesDistance: 50

# Filter ORFs based on RPKM threshold
rpkmThreshold: 10.0

# Minimum length of considered ORFs. ORFs smaller than positionsInORF are filtered automatically.
lengthCutoff: 50

# Mapping methods to be considered (fiveprime, threeprime, centered, global)
mappingMethods: ["fiveprime", "threeprime"]

# Read lengths to be considered. Comma seperated string allows intervals denoted by "-" symbol (e.g. "22,23,27,34-35")
readLengths: "32,56"

# Normalization method (raw, cpm, window)
# raw: no normalization, raw read counts
# cpm: counts per million normalization (CPM)
# window: normalized data by total counts and considered window length.
normalizationMethods: ["raw", "cpm"]

### Plotting
# Plot output types. Supported (svg, pdf, png, jpg, interactive)
outputFormats: ["interactive"]

# Interactive html files require more space as they require plotly.js integrated, online access or a local copy of plotly.js
# integrated: integrates plotly.js into each plot (+-3.7mb per file)
# online: references an online version of plotly.js (files can only be used with active internet connection)
# local: references a local plotly.js script (requires a local copy of plotly.js to open the plots)
includePlotlyJS: "integrated"

# Custom list of colors to be used for the plots. Must be atleast as many as the number of read lengths considered.
# If empty we try to match the number of read lengths trying to prioritize color-blind friendly colors.
colorList: []
